name: release-dict

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install deps
      run: sudo apt-get install -y liblwp-protocol-https-perl skktools libwww-perl cpanminus

    - name: Install cpan modules
      run: sudo cpanm -nv Lingua::JA::Regular::Unicode

    - name: Build dictionary
      run: perl download.pl

    - name: Commit dictionary
      run: |
        git config --global user.email "tokuhirom@gmail.com"
        git config --global user.name "tokuhirom by github actions"
        git add SKK-JISYO.neologd
        git diff --cached --quiet || git commit -m 'Update dictionary' && git push origin master

    - name: Create release
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        VERSION=$(date +'%Y.%m.%d.%H%M%S')
        gh release create "$VERSION" \
          --title "SKK-JISYO.neologd $VERSION" \
          --notes "Dictionary built from mecab-ipadic-neologd" \
          SKK-JISYO.neologd
